apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cake-delight
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 3004
      targetPort: 3004
