apiVersion: v1
kind: ConfigMap
metadata:
  name: cake-delight-config
  namespace: cake-delight
  labels:
    app.kubernetes.io/name: cake-delight
data:
  CATALOG_SERVICE_URL: "http://catalog-service:3001"
  ORDER_SERVICE_URL: "http://order-service:3002"
  RATING_SERVICE_URL: "http://rating-service:3003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3004"
  CATALOG_MONGO_URI: "mongodb://mongodb:27017/cake_catalog_db"
  ORDER_MONGO_URI: "mongodb://mongodb:27017/order_db"
  RATING_MONGO_URI: "mongodb://mongodb:27017/rating_db"
  NOTIFICATION_MONGO_URI: "mongodb://mongodb:27017/notification_db"
