apiVersion: v1
kind: Secret
metadata:
  name: cake-delight-secret
  namespace: cake-delight
  labels:
    app.kubernetes.io/name: cake-delight
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "cakedelight"
  RABBITMQ_DEFAULT_PASS: "cakedelight"
  RABBITMQ_URL: "amqp://cakedelight:cakedelight@rabbitmq:5672"
