apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cake-delight
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nemo0110/cake-delight-order-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: ORDER_MONGO_URI
            - name: CATALOG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: CATALOG_SERVICE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: cake-delight-secret
                  key: RABBITMQ_URL
          readinessProbe:
            tcpSocket:
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
