apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  namespace: cake-delight
  labels:
    app: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: nemo0110/cake-delight-rating-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: RATING_MONGO_URI
          readinessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5
