apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: cake-delight
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - port: 3001
      targetPort: 3001
